name: prj4
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - setuptools
  - wheel
  - bzip2
  - ca-certificates
  - expat
  - libffi
  - ncurses
  - openssl
  - readline
  - sqlite
  - tk
  - tzdata
  - xz
  - zlib

  - pip:
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - idna==3.11
      - requests==2.32.5
      - urllib3==2.6.2
